development:
  adapter: postgresql
  database: fruit_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fruit_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fruit_production
  pool: 5
  timeout: 5000
